language: android
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew build check --daemon"